# Generated by Django 5.1.3 on 2024-12-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FEEDBACK', models.CharField(max_length=200)),
                ('POINTS', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STUDENT_NAME', models.CharField(max_length=100)),
                ('FATHER_NAME', models.CharField(max_length=100)),
                ('GENDER', models.CharField(max_length=100)),
                ('DATE_OF_BIRTH', models.CharField(max_length=100)),
                ('AGE', models.IntegerField()),
                ('RELIGION', models.CharField(max_length=100)),
                ('BLOOD_GROUP', models.CharField(max_length=100)),
                ('ADHAR_CARD_NUMBER', models.CharField(max_length=20)),
                ('SSLC_MARK', models.IntegerField()),
                ('HSC_MARK', models.IntegerField()),
                ('DEGREE', models.CharField(max_length=100)),
                ('COURSE', models.CharField(max_length=100)),
                ('STUDENT_PHONE_NUMBER', models.CharField(max_length=20)),
                ('PARENTS_PHONE_NUMBER', models.CharField(max_length=20)),
                ('EMAIL_ID', models.EmailField(max_length=254)),
                ('PASSWORD', models.CharField(max_length=100)),
                ('ADDRESS', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='joining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROOL_NUMBER', models.CharField(max_length=100)),
                ('STUDENT_NAME', models.CharField(max_length=100)),
                ('FATHER_NAME', models.CharField(max_length=100)),
                ('GENDER', models.CharField(max_length=100)),
                ('DATE_OF_BIRTH', models.CharField(max_length=100)),
                ('AGE', models.IntegerField()),
                ('RELIGION', models.CharField(max_length=100)),
                ('BLOOD_GROUP', models.CharField(max_length=100)),
                ('ADHAR_CARD_NUMBER', models.CharField(max_length=20)),
                ('FIRST_GRADUATE', models.CharField(max_length=100)),
                ('SSLC_MARK', models.IntegerField()),
                ('HSC_MARK', models.IntegerField()),
                ('DEGREE', models.CharField(max_length=100)),
                ('COURSE', models.CharField(max_length=100)),
                ('STUDENT_PHONE_NUMBER', models.CharField(max_length=20)),
                ('PARENTS_PHONE_NUMBER', models.CharField(max_length=20)),
                ('EMAIL_ID', models.EmailField(max_length=254)),
                ('PASSWORD', models.CharField(max_length=100)),
                ('ADDRESS', models.CharField(max_length=100)),
            ],
        ),
        # migrations.CreateModel(
        #     name='kamal',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=10)),
        #         ('number', models.IntegerField()),
        #     ],
        # ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROOL_NUMBER', models.CharField(max_length=100)),
                ('NAME', models.CharField(max_length=100)),
                ('DEPARTMENT', models.CharField(max_length=100)),
                ('PAPER_1', models.IntegerField()),
                ('PAPER_2', models.IntegerField()),
                ('PAPER_3', models.IntegerField()),
                ('PAPER_4', models.IntegerField()),
                ('PAPER_5', models.IntegerField()),
                ('TOTAL', models.IntegerField()),
                ('RESULT', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STAFF_ROOL_NUMBER', models.CharField(max_length=100)),
                ('STAFF_NAME', models.CharField(max_length=100)),
                ('GENDER', models.CharField(max_length=100)),
                ('DEPARTMENT', models.CharField(max_length=100)),
                ('AGE', models.IntegerField()),
                ('STAFF_PHONE_NUMBER', models.IntegerField()),
                ('EXPERNICES', models.CharField(max_length=100)),
                ('SALARY', models.CharField(max_length=100)),
            ],
        ),
    ]
