# Generated by Django 5.1.3 on 2024-12-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STUDENT_NAME', models.CharField(max_length=100)),
                ('FATHER_NAME', models.CharField(max_length=100)),
                ('GENDER', models.CharField(max_length=100)),
                ('DATE_OF_BIRTH', models.CharField(max_length=100)),
                ('AGE', models.IntegerField()),
                ('RELIGION', models.CharField(max_length=100)),
                ('BLOOD_GROUP', models.CharField(max_length=100)),
                ('ADHAR_CARD_NUMBER', models.IntegerField()),
                ('SSLC_MARK', models.IntegerField()),
                ('HSC_MARK', models.IntegerField()),
                ('DEGREE', models.CharField(max_length=100)),
                ('COURSE', models.CharField(max_length=100)),
                ('STUDENT_PHONE_NUMBER', models.IntegerField()),
                ('PARENTS_PHONE_NUMBER', models.IntegerField()),
                ('EMAIL_ID', models.EmailField(max_length=254)),
                ('PASSWORD', models.CharField(max_length=100)),
                ('ADDRESS', models.CharField(max_length=100)),
            ],
        ),
    ]
